/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidentOverviewRouteImport } from './routes/resident.overview'
import { Route as ResidentIncomeRouteImport } from './routes/resident.income'
import { Route as ResidentDrilldownRouteImport } from './routes/resident.drilldown'
import { Route as ResidentCashflowRouteImport } from './routes/resident.cashflow'
import { Route as ResidentBalanceRouteImport } from './routes/resident.balance'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResidentsRouteImport } from './routes/admin.residents'
import { Route as AdminIncomeRouteImport } from './routes/admin.income'
import { Route as AdminImportsRouteImport } from './routes/admin.imports'
import { Route as AdminEtlRouteImport } from './routes/admin.etl'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminActionsRouteImport } from './routes/admin.actions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentOverviewRoute = ResidentOverviewRouteImport.update({
  id: '/resident/overview',
  path: '/resident/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentIncomeRoute = ResidentIncomeRouteImport.update({
  id: '/resident/income',
  path: '/resident/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentDrilldownRoute = ResidentDrilldownRouteImport.update({
  id: '/resident/drilldown',
  path: '/resident/drilldown',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentCashflowRoute = ResidentCashflowRouteImport.update({
  id: '/resident/cashflow',
  path: '/resident/cashflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentBalanceRoute = ResidentBalanceRouteImport.update({
  id: '/resident/balance',
  path: '/resident/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResidentsRoute = AdminResidentsRouteImport.update({
  id: '/admin/residents',
  path: '/admin/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIncomeRoute = AdminIncomeRouteImport.update({
  id: '/admin/income',
  path: '/admin/income',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportsRoute = AdminImportsRouteImport.update({
  id: '/admin/imports',
  path: '/admin/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEtlRoute = AdminEtlRouteImport.update({
  id: '/admin/etl',
  path: '/admin/etl',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/admin/collections',
  path: '/admin/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActionsRoute = AdminActionsRouteImport.update({
  id: '/admin/actions',
  path: '/admin/actions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/etl': typeof AdminEtlRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/resident/balance': typeof ResidentBalanceRoute
  '/resident/cashflow': typeof ResidentCashflowRoute
  '/resident/drilldown': typeof ResidentDrilldownRoute
  '/resident/income': typeof ResidentIncomeRoute
  '/resident/overview': typeof ResidentOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/etl': typeof AdminEtlRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/resident/balance': typeof ResidentBalanceRoute
  '/resident/cashflow': typeof ResidentCashflowRoute
  '/resident/drilldown': typeof ResidentDrilldownRoute
  '/resident/income': typeof ResidentIncomeRoute
  '/resident/overview': typeof ResidentOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/etl': typeof AdminEtlRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/resident/balance': typeof ResidentBalanceRoute
  '/resident/cashflow': typeof ResidentCashflowRoute
  '/resident/drilldown': typeof ResidentDrilldownRoute
  '/resident/income': typeof ResidentIncomeRoute
  '/resident/overview': typeof ResidentOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/actions'
    | '/admin/alerts'
    | '/admin/audit'
    | '/admin/collections'
    | '/admin/etl'
    | '/admin/imports'
    | '/admin/income'
    | '/admin/residents'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/vendors'
    | '/resident/balance'
    | '/resident/cashflow'
    | '/resident/drilldown'
    | '/resident/income'
    | '/resident/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/actions'
    | '/admin/alerts'
    | '/admin/audit'
    | '/admin/collections'
    | '/admin/etl'
    | '/admin/imports'
    | '/admin/income'
    | '/admin/residents'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/vendors'
    | '/resident/balance'
    | '/resident/cashflow'
    | '/resident/drilldown'
    | '/resident/income'
    | '/resident/overview'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/actions'
    | '/admin/alerts'
    | '/admin/audit'
    | '/admin/collections'
    | '/admin/etl'
    | '/admin/imports'
    | '/admin/income'
    | '/admin/residents'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/vendors'
    | '/resident/balance'
    | '/resident/cashflow'
    | '/resident/drilldown'
    | '/resident/income'
    | '/resident/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminActionsRoute: typeof AdminActionsRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminEtlRoute: typeof AdminEtlRoute
  AdminImportsRoute: typeof AdminImportsRoute
  AdminIncomeRoute: typeof AdminIncomeRoute
  AdminResidentsRoute: typeof AdminResidentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  ResidentBalanceRoute: typeof ResidentBalanceRoute
  ResidentCashflowRoute: typeof ResidentCashflowRoute
  ResidentDrilldownRoute: typeof ResidentDrilldownRoute
  ResidentIncomeRoute: typeof ResidentIncomeRoute
  ResidentOverviewRoute: typeof ResidentOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/overview': {
      id: '/resident/overview'
      path: '/resident/overview'
      fullPath: '/resident/overview'
      preLoaderRoute: typeof ResidentOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/income': {
      id: '/resident/income'
      path: '/resident/income'
      fullPath: '/resident/income'
      preLoaderRoute: typeof ResidentIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/drilldown': {
      id: '/resident/drilldown'
      path: '/resident/drilldown'
      fullPath: '/resident/drilldown'
      preLoaderRoute: typeof ResidentDrilldownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/cashflow': {
      id: '/resident/cashflow'
      path: '/resident/cashflow'
      fullPath: '/resident/cashflow'
      preLoaderRoute: typeof ResidentCashflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/balance': {
      id: '/resident/balance'
      path: '/resident/balance'
      fullPath: '/resident/balance'
      preLoaderRoute: typeof ResidentBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/residents': {
      id: '/admin/residents'
      path: '/admin/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof AdminResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/income': {
      id: '/admin/income'
      path: '/admin/income'
      fullPath: '/admin/income'
      preLoaderRoute: typeof AdminIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/etl': {
      id: '/admin/etl'
      path: '/admin/etl'
      fullPath: '/admin/etl'
      preLoaderRoute: typeof AdminEtlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/imports': {
      id: '/admin/imports'
      path: '/admin/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AdminImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/admin/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/actions': {
      id: '/admin/actions'
      path: '/admin/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AdminActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminActionsRoute: AdminActionsRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminEtlRoute: AdminEtlRoute,
  AdminImportsRoute: AdminImportsRoute,
  AdminIncomeRoute: AdminIncomeRoute,
  AdminResidentsRoute: AdminResidentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  ResidentBalanceRoute: ResidentBalanceRoute,
  ResidentCashflowRoute: ResidentCashflowRoute,
  ResidentDrilldownRoute: ResidentDrilldownRoute,
  ResidentIncomeRoute: ResidentIncomeRoute,
  ResidentOverviewRoute: ResidentOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
